---
title: "Interactive Hydrogrphy in Lake Champlain with mapview popup"
---

```{r set-options, echo=FALSE, cache=FALSE}
options(width = 10)
```

```{r setup, include=FALSE}
#knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.width = 9.5, message = FALSE)
```

---

* __html__ example:
Hydrographs from National Water Model in the Great Lakes
```{r message = F, resutls = "hide", warning = F}
library(tidyverse)
library(mapview)
library(sp)
library(lattice)
```

### Load stations
```{r warning = F}
pnt             <- read.csv("P:/ipemf/wrf/Champlain/RMD/Station_Champlain.csv")
pnt$NAME        <- paste0("0", pnt$NAME)
pnt$Avail       <- FALSE
```
### Load hydrographs
*somehow local images cannot be popuped by mapview*
```{r}
#img   <- character(npnt)
rpnt  <- nrow(pnt)
for (i in 1 : rpnt) {
    filename <- paste0("P:/ipemf/wrf/Champlain/Stream/US/Champlain_hydrograph_comp_", pnt$NAME[i], ".png")
  if (file.exists(filename)){
    pnt$Avail[i] <- TRUE
  }
}

pnt <- pnt[pnt$Avail, ]
npnt  <- nrow(pnt)
img <- paste0("http://www-personal.umich.edu/~cxiao/Champlain_Hydrograph/Champlain_hydrograph_comp_", 
              pnt$NAME, ".png")

```
### Spatial points
```{r}
coordinates(pnt) <- ~ LON + LAT
proj4string(pnt) <- "+init=epsg:4326"

```

#### Add the Great Lakes watershed polygon
```{r message = F, resutls = "hide", warning = F}
library(rgdal)
rBasin       <- readOGR(dsn = "P:/ipemf/wrf/Champlain/RMD/LC_polygons", layer = "lake_champlain_basin_simplified")
rBasin.proj  <- spTransform(rBasin, CRSobj = CRS(proj4string(pnt)))

rLake       <- readOGR(dsn = "P:/ipemf/wrf/Champlain/RMD/LC_polygons", layer = "lake_champlain_simplified")
rLake.proj  <- spTransform(rLake, CRSobj = CRS(proj4string(pnt)))
```

### Draw plot
```{r}
mapview(pnt, label = pnt$NAME, layer.name = "Hydrographs", 
        popup = popupImage(img, src = "remote"), cex = 5) +
  mapview(rBasin.proj, layer.name = "Watershed", fill = F) +
  mapview(rLake.proj, layer.name = "Lake", fill = F)
```
</br>
</br>
</br>
</br>
Use different colors to differenciate stations with and without hydrographs
</br>
</br>
</br>
</br>
Change the popup Image size